version: '3'

services:

    db:
      image: mysql
      restart: always
      command: --default-authentication-plugin=mysql_native_password
      volumes:
        - /home/smia/db_data
      ports:
        - 3306:3306
      environment:
        - MYSQL_ROOT_PASSWORD=abdu123
        - MYSQL_DATABASE=ft_database
        - MYSQL_USER=amya  # Replace with your desired MySQL username
        - MYSQL_PASSWORD=amya123  # Replace with your desired MySQL password

    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
