 const categoriesData = [
    ['Sports and Fitness'],
    ['Arts and Crafts'],
    ['Music'],
    ['Food and Cooking'],
    ['Gaming'],
    ['Travel and Adventure'],
    ['Technology and Coding'],
    ['Health and Wellness'],
    ['Literature and Writing'],
    ['Science and Nature'],
  ];


 const interestsData = [

['Soccer', 1],
['Basketball', 1],
['Running', 1],
['Yoga', 1],
['Swimming', 1],
['Cycling', 1],
['Gymnastics', 1],
['Tennis', 1],
['Martial Arts', 1],
['Volleyball', 1],

['Painting', 2],
['Drawing', 2],
['Photography', 2],
['Pottery', 2],
['Sculpting', 2],
['Calligraphy', 2],
['Knitting', 2],
['Origami', 2],
['Jewelry Making', 2],
['Woodworking', 2],

['Playing Guitar', 3],
['Playing Piano', 3],
['Singing', 3],
['Drumming', 3],
['DJing', 3],
['Songwriting', 3],
['Classical Music', 3],
['Electronic Music', 3],
['Jazz', 3],
['Hip Hop', 3],

['Baking', 4],
['Cooking Italian Cuisine', 4],
['Grilling', 4],
['Vegan Cooking', 4],
['Sushi Making', 4],
['Dessert Making', 4],
['Indian Cuisine', 4],
['Thai Cuisine', 4],
['Mexican Cuisine', 4],
['Mediterranean Diet', 4],

['Video Games', 5],
['Board Games', 5],
['Card Games', 5],
['Role-Playing Games [RPGs]', 5],
['Strategy Games', 5],
['Puzzle Games', 5],
['eSports', 5],
['Mobile Gaming', 5],
['Tabletop Games', 5],
['Adventure Games', 5],

['Hiking', 6],
['Backpacking', 6],
['Camping', 6],
['Road Trips', 6],
['International Travel', 6],
['Solo Traveling', 6],
['Wildlife Photography', 6],
['Mountain Climbing', 6],
['Beach Getaways', 6],
['Cultural Exploration', 6],

['Programming', 7],
['Web Development', 7],
['App Development', 7],
['Artificial Intelligence', 7],
['Machine Learning', 7],
['Cybersecurity', 7],
['Robotics', 7],
['3D Printing', 7],
['Virtual Reality', 7],
['Augmented Reality', 7],

['Meditation', 8],
['Mindfulness', 8],
['Healthy Eating', 8],
['Fitness Tracking', 8],
['Mental Health', 8],
['Self-Care', 8],
['Wellness Retreats', 8],
['Holistic Healing', 8],
['Weightlifting', 8],
['Personal Training', 8],

['Reading Fiction', 9],
['Poetry Writing', 9],
['Creative Writing', 9],
['Book Clubs', 9],
['Journaling', 9],
['Storytelling', 9],
['Fantasy Novels', 9],
['Historical Fiction', 9],
['Science Fiction', 9],
['Mystery and Thrillers', 9],

['Astronomy', 10],
['Biology', 10],
['Physics', 10],
['Environmental Conservation', 10],
['Bird Watching', 10],
['Botany', 10],
['Zoology', 10],
['Meteorology', 10],
['Geology', 10],
['Marine Biology', 10],
]


module.exports = {
    categoriesData,
    interestsData,
};